FROM mcr.microsoft.com/devcontainers/cpp:1-ubuntu-24.04

RUN apt-get update && apt-get install -y \
    valgrind \
    clang-format-17 \
    build-essential \
    cmake \
    && rm -rf /var/lib/apt/lists/*



